import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.PopularBlog}>Popular Blogs</h1>
        <div className={styles.container}>
          <h2 className={styles.BlogTitle}>Hello World!!!</h2>
          <p className={styles.BlogBody}>this is the body section</p>
        </div>
        <div className={styles.container}>
          <h2 className={styles.BlogTitle}>Hello World!!!</h2>
          <p className={styles.BlogBody}>this is the body section</p>
        </div>
        <div className={styles.container}>
          <h2 className={styles.BlogTitle}>Hello World!!!</h2>
          <p className={styles.BlogBody}>this is the body section</p>
        </div>
        <div className={styles.container}>
          <h2 className={styles.BlogTitle}>Hello World!!!</h2>
          <p className={styles.BlogBody}>this is the body section</p>
        </div>
      </main>
    </>
  )
}
